
List<String> dataListlokasi=[
"Banda Aceh",
"Langsa",
"Lhokseumawe",
"Sabang",
"Subulussalam",
"Denpasar",
"Pangkalpinang",
"Cilegon",
"Serang",
"Tangerang Selatan",
"Tangerang",
"Bengkulu",
"Yogyakarta",
"Gorontalo",
"Kota Administrasi Jakarta Barat",
"Kota Administrasi Jakarta Pusat",
"Kota Administrasi Jakarta Selatan",
"Kota Administrasi Jakarta Timur",
"Kota Administrasi Jakarta Utara",
"Sungai Penuh",
"Jambi",
"Bandung",
"Bekasi",
"Bogor",
"Cimahi",
"Cirebon",
"Depok",
"Sukabumi",
"Tasikmalaya",
"Banjar",
"Magelang",
"Pekalongan",
"Salatiga",
"Semarang",
"Surakarta",
"Tegal",
"Batu",
"Blitar",
"Kediri",
"Madiun",
"Malang",
"Mojokerto",
"Pasuruan",
"Probolinggo",
"Surabaya",
"Pontianak",
"Singkawang",
"Banjarbaru",
"Banjarmasin",
"Palangka Raya",
"Balikpapan",
"Bontang",
"Samarinda",
"Nusantara",
"Tarakan",
"Batam",
"Tanjungpinang",
"Bandar Lampung",
"Metro",
"Ternate",
"Tidore Kepulauan",
"Ambon",
"Tual",
"Bima",
"Mataram",
"Kupang",
"Sorong",
"Jayapura",
"Dumai",
"Pekanbaru",
"Makassar",
"Palopo",
"Parepare",
"Palu",
"Baubau",
"Kendari",
"Bitung",
"Kotamobagu",
"Manado",
"Tomohon",
"Bukittinggi",
"Padang",
"Padang Panjang",
"Pariaman",
"Payakumbuh",
"Sawahlunto",
"Solok",
"Lubuklinggau",
"Pagar Alam",
"Palembang",
"Prabumulih",
"Binjai",
"Gunungsitoli",
"Medan",
"Padangsidimpuan",
"Pematangsiantar",
"Sibolga",
"Tanjungbalai",
"Tebing Tingg",
"Aceh Barat Daya",
"Aceh Barat",
"Aceh Besar",
"Aceh Jaya",
"Aceh Selatan",
"Aceh Singkil",
"Aceh Tamiang",
"Aceh Tengah",
"Aceh Tenggara",
"Aceh Timur",
"Aceh Utara",
"Agam",
"Alor",
"Asahan",
"Asmat",
"Badung",
"Balangan",
"Bandung Barat",
"Bandung",
"Banggai",
"Banggai Kepulauan",
"Banggai Laut",
"Bangka Barat",
"Bangka Selatan",
"Bangka Tengah",
"Bangka",
"Bangkalan",
"Bangli",
"Banjar",
"Banjarnegara",
"Bantaeng",
"Bantul",
"Banyuasin",
"Banyumas",
"Banyuwangi",
"Barito Kuala",
"Barito Selatan",
"Barito Timur",
"Barito Utara",
"Barru",
"Batang",
"Batanghari",
"Batubara",
"Bekasi",
"Belitung Timur",
"Belitung",
"Belu",
"Bener Meriah",
"Bengkalis",
"Bengkayang",
"Bengkulu Selatan",
"Bengkulu Tengah",
"Bengkulu Utara",
"Berau",
"Biak Numfor",
"Bima",
"Bintan",
"Bireuen",
"Blitar",
"Blora",
"Boalemo",
"Bogor",
"Bojonegoro",
"Bolaang Mongondow",
"Bolaang Mongondow Selatan",
"Bolaang Mongondow Timur",
"Bolaang Mongondow Utara",
"Bombana",
"Bondowoso",
"Bone Bolango",
"Bone",
"Boven Digoel",
"Boyolali",
"Brebes",
"Buleleng",
"Bulukumba",
"Bulungan",
"Bungo",
"Buol",
"Buru Selatan",
"Buru",
"Buton",
"Buton Selatan",
"Buton Tengah",
"Buton Utara",
"Ciamis",
"Cianjur",
"Cilacap",
"Cirebon",
"Dairi",
"Deiyai",
"Deli Serdang",
"Demak",
"Dharmasraya",
"Dogiyai",
"Dompu",
"Donggala",
"Empat Lawang",
"Ende",
"Enrekang",
"Fakfak",
"Flores Timur",
"Garut",
"Gayo Lues",
"Gianyar",
"Gorontalo Utara",
"Gorontalo",
"Gowa",
"Gresik",
"Grobogan",
"Gunung Kidul",
"Gunung Mas",
"Halmahera Barat",
"Halmahera Selatan",
"Halmahera Tengah",
"Halmahera Timur",
"Halmahera Utara",
"Hulu Sungai Selatan",
"Hulu Sungai Tengah",
"Hulu Sungai Utara",
"Humbang Hasundutan",
"Indragiri Hilir",
"Indragiri Hulu",
"Indramayu",
"Intan Jaya",
"Jayapura",
"Jayawijaya",
"Jember",
"Jembrana",
"Jeneponto",
"Jepara",
"Jombang",
"Kaimana",
"Kampar",
"Kapuas Hulu",
"Kapuas",
"Karanganyar",
"Karangasem",
"Karawang",
"Karimun",
"Karo",
"Katingan",
"Kaur",
"Kayong Utara",
"Kebumen",
"Kediri",
"Keerom",
"Kendal",
"Kepahiang",
"Kepulauan Anambas",
"Kepulauan Aru",
"Kepulauan Mentawai",
"Kepulauan Meranti",
"Kepulauan Sangihe",
"Kepulauan Selayar",
"Administrasi Kepulauan Seribu",
"Kepulauan Siau Tagulandang Biaro",
"Kepulauan Sula",
"Kepulauan Talaud",
"Kepulauan Yapen",
"Kerinci",
"Ketapang",
"Klaten",
"Klungkung",
"Kolaka",
"Kolaka Timur",
"Kolaka Utara",
"Konawe Kepulauan",
"Konawe Selatan",
"Konawe Utara",
"Konawe",
"Kotabaru",
"Kotawaringin Barat",
"Kotawaringin Timur",
"Kuantan Singingi",
"Kubu Raya",
"Kudus",
"Kulon Progo",
"Kuningan",
"Kupang",
"Kutai Barat",
"Kutai Kartanegara",
"Kutai Timur",
"Labuhanbatu Selatan",
"Labuhanbatu Utara",
"Labuhanbatu",
"Lahat",
"Lamandau",
"Lamongan",
"Lampung Barat",
"Lampung Selatan",
"Lampung Tengah",
"Lampung Timur",
"Lampung Utara",
"Landak",
"Langkat",
"Lanny Jaya",
"Lebak",
"Lebong",
"Lembata",
"Lima Puluh Kota",
"Lingga",
"Lombok Barat",
"Lombok Tengah",
"Lombok Timur",
"Lombok Utara",
"Lumajang",
"Luwu",
"Luwu Timur",
"Luwu Utara",
"Madiun",
"Magelang",
"Magetan",
"Mahakam Ulu",
"Majalengka",
"Majene",
"Malaka",
"Malang",
"Malinau",
"Maluku Barat Daya",
"Maluku Tengah",
"Maluku Tenggara Barat",
"Maluku Tenggara",
"Mamasa",
"Mamberamo Raya",
"Mamberamo Tengah",
"Mamuju",
"Mamuju Tengah",
"Mamuju Utara",
"Mandailing Natal",
"Manggarai Barat",
"Manggarai Timur",
"Manggarai",
"Manokwari",
"Manokwari Selatan",
"Mappi",
"Maros",
"Maybrat",
"Melawi",
"Merangin",
"Merauke",
"Mesuji",
"Mimika",
"Minahasa",
"Minahasa Selatan",
"Minahasa Tenggara",
"Minahasa Utara",
"Mojokerto",
"Morowali",
"Morowali Utara",
"Muara Enim",
"Muaro Jambi",
"Mukomuko",
"Muna",
"Muna Barat",
"Murung Raya",
"Musi Banyuasin",
"Musi Rawas",
"Musi Rawas Utara",
"Nabire",
"Nagan Raya",
"Nagekeo",
"Natuna",
"Nduga",
"Ngada",
"Nganjuk",
"Ngawi",
"Nias Barat",
"Nias Selatan",
"Nias Utara",
"Nias",
"Nunukan",
"Ogan Ilir",
"Ogan Komering Ilir",
"Ogan Komering Ulu Selatan",
"Ogan Komering Ulu Timur",
"Ogan Komering Ulu",
"Pacitan",
"Padang Lawas Utara",
"Padang Lawas",
"Padang Pariaman",
"Pakpak Bharat",
"Pamekasan",
"Pandeglang",
"Pangandaran",
"Pangkajene dan Kepulauan",
"Paniai",
"Parigi Moutong",
"Pasaman Barat",
"Pasaman",
"Paser",
"Pasuruan",
"Pati",
"Pegunungan Arfak",
"Pegunungan Bintang",
"Pekalongan",
"Pelalawan",
"Pemalang",
"Penajam Paser Utara",
"Penukal Abab Lematang Ilir",
"Pesawaran",
"Pesisir Barat",
"Pesisir Selatan",
"Pidie Jaya",
"Pidie",
"Pinrang",
"Pohuwato",
"Polewali Mandar",
"Ponorogo",
"Mempawah",
"Poso",
"Pringsewu",
"Probolinggo",
"Pulang Pisau",
"Pulau Morotai",
"Pulau Taliabu",
"Puncak Jaya",
"Puncak",
"Purbalingga",
"Purwakarta",
"Purworejo",
"Raja Ampat",
"Rejang Lebong",
"Rembang",
"Rokan Hilir",
"Rokan Hulu",
"Rote Ndao",
"Sabu Raijua",
"Sambas",
"Samosir",
"Sampang",
"Sanggau",
"Sarmi",
"Sarolangun",
"Sekadau",
"Seluma",
"Semarang",
"Seram Bagian Barat",
"Seram Bagian Timur",
"Serang",
"Serdang Bedagai",
"Seruyan",
"Siak",
"Sidenreng Rappang",
"Sidoarjo",
"Sigi",
"Sijunjung",
"Sikka",
"Simalungun",
"Simeulue",
"Sinjai",
"Sintang",
"Situbondo",
"Sleman",
"Solok Selatan",
"Solok",
"Soppeng",
"Sorong",
"Sorong Selatan",
"Sragen",
"Subang",
"Sukabumi",
"Sukamara",
"Sukoharjo",
"Sumba Barat Daya",
"Sumba Barat",
"Sumba Tengah",
"Sumba Timur",
"Sumbawa Barat",
"Sumbawa",
"Sumedang",
"Sumenep",
"Supiori",
"Tabalong",
"Tabanan",
"Takalar",
"Tambrauw",
"Tana Tidung",
"Tana Toraja",
"Tanah Bumbu",
"Tanah Datar",
"Tanah Laut",
"Tangerang",
"Tanggamus",
"Tanjung Jabung Barat",
"Tanjung Jabung Timur",
"Tapanuli Selatan",
"Tapanuli Tengah",
"Tapanuli Utara",
"Tapin",
"Tasikmalaya",
"Tebo",
"Tegal",
"Teluk Bintuni",
"Teluk Wondama",
"Temanggung",
"Timor Tengah Selatan",
"Timor Tengah Utara",
"Toba Samosir",
"Tojo Una-Una",
"Toli-Toli",
"Tolikara",
"Toraja Utara",
"Trenggalek",
"Tuban",
"Tulang Bawang Barat",
"Tulang Bawang",
"Tulungagung",
"Wajo",
"Wakatobi",
"Waropen",
"Way Kanan",
"Wonogiri",
"Wonosobo",
"Yahukimo",
"Yalimo",
];